<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
      <groupId>ngz.markov</groupId>
      <artifactId>meteofrance-java-sdk</artifactId>
      <version>2</version>
      <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>meteofrance-paquet</artifactId>
  <version>0.1.0</version>

  <name>meteofrance-paquet</name>

  <properties>
    <jackson.version>3.1.2</jackson.version>
    <lombok.version>1.18.46</lombok.version>
  <extraSurefireArgs>
      --add-opens ngz.meteofrance.paquet/ngz.meteofrance.paquet.api=ALL-UNNAMED
      --add-opens ngz.meteofrance.paquet/ngz.meteofrance.paquet.mapper=ALL-UNNAMED
  </extraSurefireArgs>
  </properties>

  <dependencyManagement>
    <dependencies>
    </dependencies>
  </dependencyManagement>

  <dependencies>
        <dependency>
          <groupId>ngz.markov</groupId>
          <artifactId>meteofrance-core</artifactId>
          <version>0.1.0</version>
          <scope>provided</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency> 
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-core -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>3.1.2</version>
            <scope>compile</scope>
        </dependency>

        <!-- Source: https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>

      <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
          <scope>compile</scope>
      </dependency>
  </dependencies>

  <build>
    <pluginManagement>
    </pluginManagement>
      <plugins>
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-compiler-plugin</artifactId>
              <configuration>
                  <annotationProcessorPaths>
                      <path>
                          <groupId>org.projectlombok</groupId>
                          <artifactId>lombok</artifactId>
                          <version>${lombok.version}</version>
                      </path>
                  </annotationProcessorPaths>
              </configuration>

          </plugin>
      </plugins>
  </build>
</project>
